apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: service-b-pipeline
spec:
  description: Service B's pipeline.
  params:
    - name: service
      type: string
  tasks:
    - name: task
      taskRef:
        name: echo-val-task
      params:
        - name: service
          value: $(params.service)
